apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: repairmate
        tier: backend
  template:
    metadata:
      labels:
        app: repairmate
        tier: backend
    spec:
      containers:
      - name: back
        image: harshil3662/repairmate-backend:v1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: my-backend-config