apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: repairmate
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002
  selector:
    app: repairmate
    tier: backend