apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: repairmate
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 3000        
    targetPort: 3000  
  selector:
    app: repairmate
    tier: frontend
