apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: repairmate
        tier: backend
  template:
    metadata:
      labels:
        app: repairmate
        tier: backend
    spec:
      containers:
      - name: back
        image: harshil3662/repairmate-backend:latest
        ports:
        - containerPort: 8000
        env: 
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: mongo-uri
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: access-token-secret
        - name: ACCESS_TOKEN_EXPIRY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: access-token-expiry
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: refresh-token-secret
        - name: REFRESH_TOKEN_EXPIRY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: refresh-token-expiry