apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly92YWdoYW5paGFyc2hpbDExMjkxOlh5aU1NSERyQUF6c2tQbXZAY2x1c3RlcjAueW04ZHQubW9uZ29kYi5uZXQ=
  access-token-secret: UWZndHlmdGZBRFNEU0RGZ2ZnaGZoZ2ZoZ2hnY2ZjZmNmZ2NmZ2NkZmhmZ2p0cmQzNDU1NTc3dGZodGZXU0Y=
  access-token-expiry: MWQ=
  refresh-token-secret: RERmaGZkZmhmM3c1MzRldTU2cjZ5dHVmU1NETkJGZHlnanksZ2YsanlmZ2pmalNHU1NCRmdmZGdmZG5nZmQ=
  refresh-token-expiry: MTBk
