name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker images for backend
      working-directory: ./backend
      run: |
        docker build -t harshil3662/repairmate-backend .
        docker push harshil3662/repairmate-backend

    - name: Build and push the Docker images for frontend
      working-directory: ./frontend
      run: |
        docker build -t harshil3662/repairmate-frontend .
        docker push harshil3662/repairmate-frontend
